# Generated by Django 2.2.6 on 2019-10-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('document_classification', 'Document Classification'), ('sequence_labeling', 'Sequence Labeling'), ('seq2seq', 'Sequence to Sequence')], max_length=30),
        ),
    ]
