# Generated by Django 2.2.6 on 2019-10-25 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_project_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.OneToOneField(default=43, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
