# Generated by Django 2.2.6 on 2019-10-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191025_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('TextClassificationProject', 'Document Classification'), ('SequenceLabelingProject', 'Sequence Labeling'), ('Seq2seqProject', 'Sequence to Sequence')], max_length=30),
        ),
    ]
