# Generated by Django 2.2.6 on 2019-11-21 15:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20191116_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfLabelingProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Project')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.project',),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('TextClassificationProject', 'Document Classification'), ('SequenceLabelingProject', 'Sequence Labeling'), ('Seq2seqProject', 'Sequence to Sequence'), ('PdfLabelingProject', 'PDF Labeling Project')], max_length=30),
        ),
        migrations.CreateModel(
            name='PdfAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.FloatField(default=0.0)),
                ('manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('position', django.contrib.postgres.fields.jsonb.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to='core.Document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user', 'label', 'content', 'position')},
            },
        ),
    ]
