# Generated by Django 2.2.6 on 2019-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191120_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('TextClassificationProject', 'Document Classification'), ('SequenceLabelingProject', 'Sequence Labeling'), ('Seq2seqProject', 'Sequence to Sequence'), ('PdfLabelingProject', 'PDF Labeling Project')], max_length=30),
        ),
    ]
