# Generated by Django 2.2.6 on 2019-11-21 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20191120_1012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdfannotation',
            unique_together={('document', 'user')},
        ),
    ]
