# Generated by Django 2.2.6 on 2019-11-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_annotator_per_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentannotation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdfannotation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seq2seqannotation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequenceannotation',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
