# Generated by Django 2.2.6 on 2019-11-21 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20191121_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdfannotation',
            unique_together={('document', 'user', 'label', 'data')},
        ),
    ]
