# Generated by Django 2.2.6 on 2019-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191127_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceannotation',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
