# Generated by Django 2.2.6 on 2019-12-16 18:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sequenceannotation_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenceannotation',
            name='text',
        ),
        migrations.AddField(
            model_name='sequenceannotation',
            name='tokens',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
